// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcT-aOy7owLORmlqsBPuJuMuD6IHKT-g',
    appId: '1:70162494968:web:b97001903812aef5c1520d',
    messagingSenderId: '70162494968',
    projectId: 'jokesapp-946da',
    authDomain: 'jokesapp-946da.firebaseapp.com',
    storageBucket: 'jokesapp-946da.firebasestorage.app',
    measurementId: 'G-405PEMMX87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhZD4WInlRvCD9VIlUvuw3DoDyYn6YsSc',
    appId: '1:70162494968:android:37e7684b77df7a74c1520d',
    messagingSenderId: '70162494968',
    projectId: 'jokesapp-946da',
    storageBucket: 'jokesapp-946da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzdKOjBpbkDoXLaexzhbgmg_nlf0L6gI',
    appId: '1:70162494968:ios:78d0cea26dbeb95ac1520d',
    messagingSenderId: '70162494968',
    projectId: 'jokesapp-946da',
    storageBucket: 'jokesapp-946da.firebasestorage.app',
    iosBundleId: 'com.example.jokesAppLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuzdKOjBpbkDoXLaexzhbgmg_nlf0L6gI',
    appId: '1:70162494968:ios:78d0cea26dbeb95ac1520d',
    messagingSenderId: '70162494968',
    projectId: 'jokesapp-946da',
    storageBucket: 'jokesapp-946da.firebasestorage.app',
    iosBundleId: 'com.example.jokesAppLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHcT-aOy7owLORmlqsBPuJuMuD6IHKT-g',
    appId: '1:70162494968:web:efb3c488839feb9fc1520d',
    messagingSenderId: '70162494968',
    projectId: 'jokesapp-946da',
    authDomain: 'jokesapp-946da.firebaseapp.com',
    storageBucket: 'jokesapp-946da.firebasestorage.app',
    measurementId: 'G-D1C0W3PR87',
  );
}
